"""empty message

Revision ID: 5520b41b32aa
Revises: 
Create Date: 2025-07-13 22:28:44.942058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5520b41b32aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('instructor', sa.String(length=100), nullable=False),
    sa.Column('topico', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cursos')
    # ### end Alembic commands ###
