"""empty message

Revision ID: 2516929916da
Revises: 
Create Date: 2025-07-23 19:32:19.090031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2516929916da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=False),
    sa.Column('comentario', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacto')
    # ### end Alembic commands ###
