"""empty message

Revision ID: fff35d13d0f7
Revises: a56d4fb448f9
Create Date: 2025-07-28 20:56:37.380244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff35d13d0f7'
down_revision = 'a56d4fb448f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frases', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['frase'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
